version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "security"
