name: Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change Directory to React
        run: cd EmbarkIt

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install --production

      - name: Run Security Checks
        run: |
          npm audit || true
          vulnerabilities=$(npm audit --json)
          echo "::set-output name=vulnerabilities::$vulnerabilities"

      - name: Check Code for Vulnerabilities
        run: npm audit --audit-level=critical || true

      - name: Add Labels to Pull Request
        uses: actions/gh@v2
        with:
          args: "issue add-labels ${{ github.event_name }} ${{ github.repository }} ${{ github.event.inputs.number }} ${{ steps.security.outputs.vulnerabilities | fromJson | keys | join(',') }}"
        if: always()
        
